#!/bin/bash
# migrate-okf-indexes.sh — Génère les index Markdown progressifs du feature mesh.
#
# Usage :
#   bash .ai/scripts/migrate-okf-indexes.sh                 # dry-run
#   bash .ai/scripts/migrate-okf-indexes.sh --apply         # écrit les index gérés
#   bash .ai/scripts/migrate-okf-indexes.sh --check         # warn-only, read-only (vN)
#   bash .ai/scripts/migrate-okf-indexes.sh --check --strict # fail si absent/périmé
#
# Les fichiers sans marqueur de génération restent project-owned : jamais écrasés.

set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=_lib.sh
. "$script_dir/_lib.sh"

repo_root="$(cd "$script_dir/../.." && pwd -P)"
cd "$repo_root"

mode="dry-run"
strict=0
for arg in "$@"; do
  case "$arg" in
    --apply) mode="apply" ;;
    --check) mode="check" ;;
    --strict) strict=1 ;;
    -h|--help)
      sed -n '1,10p' "$0" | sed 's/^# \{0,1\}//'
      exit 0
      ;;
    *)
      echo "Usage: bash .ai/scripts/migrate-okf-indexes.sh [--apply | --check [--strict]]" >&2
      exit 2
      ;;
  esac
done

if [[ "$strict" -eq 1 && "$mode" != "check" ]]; then
  echo "❌ --strict s'utilise avec --check" >&2
  exit 2
fi

case "$AI_CONTEXT_DOCS_ROOT" in
  ""|/*|*$'\n'*|*$'\r'*|*$'\t'*)
    echo "❌ docs_root invalide pour okf-indexes : chemin relatif au repo attendu." >&2
    exit 2
    ;;
esac
case "/$AI_CONTEXT_DOCS_ROOT/" in
  */../*)
    echo "❌ docs_root invalide pour okf-indexes : '..' est interdit." >&2
    exit 2
    ;;
esac

features_dir="$AI_CONTEXT_FEATURES_DIR"
features_probe="$repo_root/$features_dir"
while [[ ! -e "$features_probe" && "$features_probe" != "$repo_root" && "$features_probe" != "/" ]]; do
  features_probe="$(dirname "$features_probe")"
done
features_probe="$(cd "$features_probe" 2>/dev/null && pwd -P)" || {
  echo "❌ Impossible de résoudre docs_root pour okf-indexes." >&2
  exit 2
}
case "$features_probe" in
  "$repo_root"|"$repo_root"/*) ;;
  *)
    echo "❌ docs_root invalide pour okf-indexes : le feature mesh sort du repo." >&2
    exit 2
    ;;
esac

marker='<!-- generated by ai_context; do not edit -->'
tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/ai-context-okf-indexes.XXXXXX")"
target_tmp=""
cleanup() {
  rm -rf "$tmp_dir"
  [[ -z "$target_tmp" ]] || rm -f "$target_tmp"
}
trap cleanup EXIT

records="$tmp_dir/features.tsv"
sorted_records="$tmp_dir/features.sorted.tsv"
scopes_file="$tmp_dir/scopes.txt"
expected_dir="$tmp_dir/expected"
expected_paths="$tmp_dir/expected-paths.txt"
operations="$tmp_dir/operations.tsv"
operations_sorted="$tmp_dir/operations.sorted.tsv"
mkdir -p "$expected_dir"
: > "$records"
: > "$expected_paths"
: > "$operations"

frontmatter_scalar() {
  local file="$1"
  local key="$2"
  local value
  value="$(awk -v key="$key" '
    /^---$/ { fence++; next }
    fence != 1 { next }
    index($0, key ":") == 1 {
      line=$0
      sub("^" key ":[[:space:]]*", "", line)
      print line
      exit
    }
  ' "$file")"
  value="$(printf '%s' "$value" | sed -E 's/^[[:space:]]+//; s/[[:space:]]+$//')"
  case "$value" in
    \"*\") value="${value#\"}"; value="${value%\"}" ;;
    \'*\') value="${value#\'}"; value="${value%\'}" ;;
  esac
  printf '%s' "$value"
}

markdown_label() {
  printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/\[/\\[/g' -e 's/\]/\\]/g'
}

markdown_target() {
  local escaped
  escaped="$(printf '%s' "$1" | sed \
    -e 's/%/%25/g' \
    -e 's/ /%20/g' \
    -e 's/#/%23/g' \
    -e 's/?/%3F/g' \
    -e 's/(/%28/g' \
    -e 's/)/%29/g')"
  escaped="${escaped//$'\t'/%09}"
  escaped="${escaped//$'\r'/%0D}"
  printf '%s' "$escaped"
}

if [[ -d "$features_dir" ]]; then
  while IFS= read -r -d '' feature_file; do
    scope="$(basename "$(dirname "$feature_file")")"
    file_name="$(basename "$feature_file")"
    id="$(frontmatter_scalar "$feature_file" id)"
    title="$(frontmatter_scalar "$feature_file" title)"
    status="$(frontmatter_scalar "$feature_file" status)"
    type="$(frontmatter_scalar "$feature_file" type)"

    [[ -n "$id" ]] || id="${file_name%.md}"
    [[ -n "$title" ]] || title="$id"
    [[ -n "$status" ]] || status="?"
    [[ -n "$type" ]] || type="feature"

    case "$scope" in
      *$'\t'*|*$'\r'*)
        echo "❌ Scope incompatible avec l'index Markdown : $scope" >&2
        exit 1
        ;;
    esac
    # TSV interne : normaliser les contrôles éditoriaux ; le chemin Markdown
    # est encodé avant sérialisation pour préserver un éventuel tab du nom.
    id="${id//$'\t'/ }"; id="${id//$'\r'/ }"
    title="${title//$'\t'/ }"
    title="${title//$'\r'/ }"
    status="${status//$'\t'/ }"; status="${status//$'\r'/ }"
    type="${type//$'\t'/ }"; type="${type//$'\r'/ }"
    file_target="$(markdown_target "$file_name")"
    printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
      "$scope" "$id" "$file_target" "$title" "$status" "$type" >> "$records"
  done < <(find_feature_docs "$features_dir")
fi

LC_ALL=C sort -t $'\t' -k1,1 -k2,2 "$records" > "$sorted_records"
cut -f1 "$sorted_records" | LC_ALL=C sort -u > "$scopes_file"

while IFS= read -r scope; do
  [[ -n "$scope" ]] || continue
  mkdir -p "$expected_dir/$scope"
  scope_index="$expected_dir/$scope/index.md"
  {
    printf '%s\n\n' "$marker"
    printf '# Scope `%s`\n\n' "$scope"
    printf 'Fiches canoniques de ce scope.\n\n'
    while IFS=$'\t' read -r record_scope id file_target title status type; do
      [[ "$record_scope" == "$scope" ]] || continue
      safe_title="$(markdown_label "$title")"
      printf -- '- [%s](%s) — `%s` · `%s` · `%s`\n' \
        "$safe_title" "$file_target" "$id" "$status" "$type"
    done < "$sorted_records"
  } > "$scope_index"
  printf '%s/index.md\n' "$scope" >> "$expected_paths"
done < "$scopes_file"

root_index="$expected_dir/index.md"
{
  printf '%s\n\n' "$marker"
  printf '# Feature index\n\n'
  printf 'Navigation progressive du feature mesh.\n\n'
  if [[ -s "$scopes_file" ]]; then
    printf '## Scopes\n\n'
    while IFS= read -r scope; do
      [[ -n "$scope" ]] || continue
      count=0
      while IFS=$'\t' read -r record_scope _; do
        if [[ "$record_scope" == "$scope" ]]; then
          count=$((count + 1))
        fi
      done < "$sorted_records"
      safe_scope="$(markdown_label "$scope")"
      safe_scope_target="$(markdown_target "$scope")"
      if [[ "$count" -eq 1 ]]; then
        suffix="1 feature"
      else
        suffix="$count features"
      fi
      printf -- '- [`%s`](%s/index.md) — %s\n' "$safe_scope" "$safe_scope_target" "$suffix"
    done < "$scopes_file"
  else
    printf 'Aucune feature documentée.\n'
  fi
} > "$root_index"

{
  printf 'index.md\n'
  cat "$expected_paths"
} > "$tmp_dir/all-expected-paths.txt"
mv "$tmp_dir/all-expected-paths.txt" "$expected_paths"

is_managed_index() {
  local target="$1"
  [[ -f "$target" && ! -L "$target" ]] \
    && [[ "$(head -n 1 "$target")" == "$marker" ]]
}

record_operation() {
  printf '%s\t%s\n' "$1" "$2" >> "$operations"
}

changes=0
conflicts=0
unchanged=0

while IFS= read -r rel; do
  [[ -n "$rel" ]] || continue
  target="$features_dir/$rel"
  expected="$expected_dir/$rel"
  if [[ ! -e "$target" ]]; then
    record_operation create "$rel"
    changes=$((changes + 1))
  elif [[ ! -f "$target" ]] || ! is_managed_index "$target"; then
    record_operation conflict "$rel"
    conflicts=$((conflicts + 1))
  elif cmp -s "$expected" "$target"; then
    record_operation unchanged "$rel"
    unchanged=$((unchanged + 1))
  else
    record_operation update "$rel"
    changes=$((changes + 1))
  fi
done < "$expected_paths"

# Supprime uniquement les anciens index gérés dont le scope est devenu vide.
if [[ -d "$features_dir" ]]; then
  while IFS= read -r -d '' existing_scope_index; do
    rel="${existing_scope_index#"$features_dir"/}"
    if ! grep -Fxq "$rel" "$expected_paths" && is_managed_index "$existing_scope_index"; then
      record_operation delete "$rel"
      changes=$((changes + 1))
    fi
  done < <(find "$features_dir" -mindepth 2 -maxdepth 2 -type f -name 'index.md' -print0 2>/dev/null)
fi

LC_ALL=C sort -t $'\t' -k2,2 -k1,1 "$operations" > "$operations_sorted"

case "$mode" in
  apply) mode_label="apply" ;;
  check) mode_label="$([[ "$strict" -eq 1 ]] && echo strict || echo warn-only)" ;;
  *) mode_label="dry-run" ;;
esac
echo "═══ okf-indexes ($mode_label) ═══"

while IFS=$'\t' read -r operation rel; do
  [[ -n "$operation" ]] || continue
  if [[ "$mode" != "dry-run" && "$operation" == "unchanged" ]]; then
    continue
  fi
  printf -- '- %-9s %s/%s\n' "$operation" "$features_dir" "$rel"
done < "$operations_sorted"

pending=$((changes + conflicts))
if [[ "$mode" == "check" ]]; then
  if [[ "$pending" -eq 0 ]]; then
    echo "✓ Index Markdown présents et à jour ($unchanged inchangé(s))"
    exit 0
  fi
  if [[ "$strict" -eq 1 ]]; then
    echo "❌ Index Markdown absents, périmés ou en conflit." >&2
    echo "   Remédiation : bash .ai/scripts/aic.sh migrate okf-indexes --apply" >&2
    exit 1
  fi
  echo "⚠️  Index Markdown absents, périmés ou en conflit (warn-only vN ; CI non bloquée)." >&2
  echo "   Prévisualise : bash .ai/scripts/aic.sh migrate okf-indexes" >&2
  echo "   Applique     : bash .ai/scripts/aic.sh migrate okf-indexes --apply" >&2
  exit 0
fi

if [[ "$conflicts" -gt 0 ]]; then
  echo "❌ $conflicts index manuel ou chemin incompatible détecté : aucune écriture effectuée." >&2
  echo "   Déplace, fusionne ou marque explicitement ces fichiers avant de relancer." >&2
  exit 1
fi

if [[ "$mode" == "dry-run" ]]; then
  if [[ "$changes" -eq 0 ]]; then
    echo "✓ Aucun changement ($unchanged index inchangé(s))"
  else
    echo "ℹ️ Dry-run : $changes changement(s), $unchanged inchangé(s)."
    echo "   Relance avec --apply pour écrire les index project-owned."
  fi
  exit 0
fi

while IFS=$'\t' read -r operation rel; do
  [[ -n "$operation" ]] || continue
  target="$features_dir/$rel"
  expected="$expected_dir/$rel"
  case "$operation" in
    create|update)
      mkdir -p "$(dirname "$target")"
      target_tmp="$(mktemp "${target}.XXXXXX")"
      cp "$expected" "$target_tmp"
      chmod 0644 "$target_tmp"
      mv "$target_tmp" "$target"
      target_tmp=""
      ;;
    delete)
      rm -f "$target"
      ;;
  esac
done < "$operations_sorted"

echo "✓ $changes changement(s) appliqué(s), $unchanged index inchangé(s)"
