#!/bin/bash
# test-feature-markdown-indexes.sh — index Markdown progressifs + migration Copier.

set -euo pipefail

repo_root="$(cd "$(dirname "$0")/../.." && pwd)"
tmp="$(mktemp -d "${TMPDIR:-/tmp}/aic-feature-markdown-indexes.XXXXXX")"
trap 'rm -rf "$tmp"' EXIT

fail() {
  echo "✗ $*" >&2
  exit 1
}

copy_runtime() {
  local target="$1"
  mkdir -p "$target/.ai/scripts" "$target/.ai/schema"
  for script in \
    _lib.sh _vcs.sh aic.sh build-feature-index.sh check-features.sh \
    check-feature-docs.sh check-feature-freshness.sh check-commit-features.sh \
    migrate-features.sh migrate-okf-type.sh \
    migrate-okf-indexes.sh check-feature-indexes.sh auto-worklog-log.sh \
    fiche-consolidation-nudge.sh context-relevance-log.sh; do
    cp "$repo_root/.ai/scripts/$script" "$target/.ai/scripts/$script"
  done
  cp "$repo_root/.ai/schema/feature.schema.json" "$target/.ai/schema/feature.schema.json"
  chmod +x "$target/.ai/scripts/"*.sh
}

file_mode() {
  local mode
  mode="$(stat -f '%Lp' "$1" 2>/dev/null || true)"
  case "$mode" in
    ""|*[!0-7]*) stat -c '%a' "$1" ;;
    *) printf '%s\n' "$mode" ;;
  esac
}

write_feature() {
  local path="$1"
  local id="$2"
  local scope="$3"
  local title="$4"
  local status="${5:-active}"
  mkdir -p "$(dirname "$path")"
  {
    printf '%s\n' '---'
    printf 'id: %s\n' "$id"
    printf 'scope: %s\n' "$scope"
    printf 'title: "%s"\n' "$title"
    printf 'status: %s\n' "$status"
    printf '%s\n' 'type: feature' 'depends_on: []' 'touches: []' '---' '' "# $title"
  } > "$path"
}

main="$tmp/main"
copy_runtime "$main"
mkdir -p "$main/.docs/features/core" "$main/.docs/features/back" "$main/.docs/features/empty"
write_feature "$main/.docs/features/core/alpha.md" alpha core "Alpha [principal]"
write_feature "$main/.docs/features/back/space file.md" space-file back "Fichier avec espace"
printf '# journal réservé sans frontmatter\n' > "$main/.docs/features/back/log.md"
printf '# Worklog — core/alpha\n' > "$main/.docs/features/core/alpha.worklog.md"

# Classification centrale : seuls les deux concepts sont canoniques.
(
  cd "$main" || exit 1
  . .ai/scripts/_lib.sh || exit 1
  is_canonical_feature_doc '.docs/features/core/alpha.md' || exit 1
  is_canonical_feature_doc '.docs/features/back/space file.md' || exit 1
  ! is_canonical_feature_doc '.docs/features/core/index.md' || exit 1
  is_reserved_feature_doc '.docs/features/index.md' || exit 1
  is_reserved_feature_doc '.docs/features/core/index.md' || exit 1
  ! is_canonical_feature_doc '.docs/features/back/log.md' || exit 1
  is_feature_worklog '.docs/features/core/alpha.worklog.md' || exit 1
  count=0
  while IFS= read -r -d '' _; do count=$((count + 1)); done < <(find_feature_docs '.docs/features')
  [[ "$count" -eq 2 ]] || exit 1
) || fail "classification centrale des documents réservés incorrecte"

# Freshness : sens du retour discriminé, documents réservés exclus.
(
  cd "$main" || exit 1
  . .ai/scripts/_lib.sh || exit 1
  reference='.ai/feature-docs-reference'
  touch -t 203001010000 "$reference" || exit 1
  touch -t 202901010000 .docs/features/core/alpha.md .docs/features/back/'space file.md' || exit 1
  ! feature_docs_newer_than '.docs/features' "$reference" || exit 1
  touch -t 203101010000 .docs/features/core/alpha.md || exit 1
  feature_docs_newer_than '.docs/features' "$reference" || exit 1
  touch -t 203201010000 "$reference" || exit 1
  touch -t 203301010000 .docs/features/back/log.md .docs/features/core/alpha.worklog.md || exit 1
  ! feature_docs_newer_than '.docs/features' "$reference" || exit 1

  # Deux mtimes dans la même seconde restent ordonnés sur Bash 3.2/macOS.
  python3 - "$reference" .docs/features/core/alpha.md <<'PY' || exit 1
import os
import sys

same_second = 2_020_000_000_000_000_000
os.utime(sys.argv[1], ns=(same_second, same_second))
os.utime(sys.argv[2], ns=(same_second + 100_000_000, same_second + 100_000_000))
PY
  feature_docs_newer_than '.docs/features' "$reference" || exit 1
) || fail "feature_docs_newer_than inverse son contrat ou inclut un document réservé"

# Dry-run non mutant, puis génération multi-scope.
dry_out="$(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes)"
echo "$dry_out" | grep -q 'create.*\.docs/features/index.md' \
  || fail "dry-run ne propose pas l'index racine"
[[ ! -e "$main/.docs/features/index.md" ]] || fail "dry-run a écrit dans le repo"

(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)
for path in \
  .docs/features/index.md \
  .docs/features/core/index.md \
  .docs/features/back/index.md; do
  [[ -f "$main/$path" ]] || fail "index généré absent : $path"
  grep -Fqx '<!-- generated by ai_context; do not edit -->' "$main/$path" \
    || fail "marqueur généré absent : $path"
  [[ "$(file_mode "$main/$path")" == "644" ]] \
    || fail "mode attendu 644 pour l'index généré : $path"
done
[[ ! -e "$main/.docs/features/empty/index.md" ]] || fail "un scope vide ne doit pas avoir d'index"
grep -Fq '[Alpha \[principal\]](alpha.md)' "$main/.docs/features/core/index.md" \
  || fail "titre Markdown non échappé ou lien alpha absent"
grep -Fq '(space%20file.md)' "$main/.docs/features/back/index.md" \
  || fail "espace du chemin Markdown non encodé"
grep -Fq '[`back`](back/index.md) — 1 feature' "$main/.docs/features/index.md" \
  || fail "route racine vers le scope back absente"

# Les index/log/worklogs ne rentrent ni dans le JSON ni dans les validators/migrateurs.
json="$(cd "$main" && bash .ai/scripts/build-feature-index.sh)"
[[ "$(printf '%s' "$json" | jq '.features | length')" -eq 2 ]] \
  || fail "l'index JSON doit contenir exactement deux features"
printf '%s' "$json" | jq -e '.features | all(.path | endswith("index.md") | not)' >/dev/null \
  || fail "un index Markdown a été traité comme feature"
(cd "$main" && bash .ai/scripts/check-features.sh --no-write >/dev/null)
docs_out="$(cd "$main" && bash .ai/scripts/check-feature-docs.sh 2>&1)"
printf '%s' "$docs_out" | grep -Eq '(^|/)(index|log)\.md|\.worklog\.md' \
  && fail "check-feature-docs a traité un document réservé"
migrate_features_out="$(cd "$main" && bash .ai/scripts/migrate-features.sh 2>&1)"
printf '%s' "$migrate_features_out" | grep -Eq '(^|/)(index|log)\.md|\.worklog\.md' \
  && fail "migrate-features a traité un document réservé"
migrate_type_out="$(cd "$main" && bash .ai/scripts/migrate-okf-type.sh)"
echo "$migrate_type_out" | grep -q 'index.md' \
  && fail "migrate-okf-type a traité un index réservé"
(cd "$main" && bash .ai/scripts/check-feature-indexes.sh --strict >/dev/null)

# Idempotence stricte : contenu et sortie inchangés au second passage.
before="$(find "$main/.docs/features" -name index.md -type f -exec cksum {} \; | LC_ALL=C sort)"
unchanged_dry_out="$(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes)"
echo "$unchanged_dry_out" | grep -q 'unchanged.*\.docs/features/index.md' \
  || fail "le dry-run ne distingue pas l'index racine inchangé"
echo "$unchanged_dry_out" | grep -q 'unchanged.*core/index.md' \
  || fail "le dry-run ne distingue pas un index de scope inchangé"
second_out="$(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes --apply)"
after="$(find "$main/.docs/features" -name index.md -type f -exec cksum {} \; | LC_ALL=C sort)"
[[ "$before" == "$after" ]] || fail "un second --apply modifie les index"
echo "$second_out" | grep -q '0 changement(s) appliqué(s)' \
  || fail "la sortie du second --apply ne signale pas le no-op"
echo "$second_out" | grep -q 'unchanged' \
  && fail "--apply liste des index inchangés contrairement au contrat UX"

# Freshness warn-only vN, strict testable pour vN+1.
sed -i.bak 's/title: "Alpha \[principal\]"/title: "Alpha v2"/' "$main/.docs/features/core/alpha.md"
rm -f "$main/.docs/features/core/alpha.md.bak"
stale_before="$(cksum "$main/.docs/features/core/index.md")"
stale_dry_out="$(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes)"
echo "$stale_dry_out" | grep -q 'update.*core/index.md' \
  || fail "le dry-run ne distingue pas un index à mettre à jour"
[[ "$stale_before" == "$(cksum "$main/.docs/features/core/index.md")" ]] \
  || fail "le dry-run update a modifié un index"
warn_out="$(cd "$main" && bash .ai/scripts/check-feature-indexes.sh 2>&1)" \
  || fail "le check warn-only ne doit pas casser la CI"
echo "$warn_out" | grep -q 'update.*core/index.md' \
  || fail "le check warn-only ne détecte pas l'index périmé"
strict_rc=0
(cd "$main" && bash .ai/scripts/check-feature-indexes.sh --strict >/tmp/aic-feature-indexes-strict-test.out 2>&1) \
  || strict_rc=$?
[[ "$strict_rc" -eq 1 ]] || fail "le check strict doit échouer sur index périmé"
grep -q 'migrate okf-indexes --apply' /tmp/aic-feature-indexes-strict-test.out \
  || fail "le check strict ne donne pas la commande de remédiation"
rm -f /tmp/aic-feature-indexes-strict-test.out
(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)

# Collision manuelle : préflight transactionnel, aucune écriture partielle.
{
  printf '# Index manuel à préserver\n\n'
  printf 'Le marqueur cité plus bas ne transfère pas la propriété.\n'
  printf '<!-- generated by ai_context; do not edit -->\n'
} > "$main/.docs/features/back/index.md"
core_before="$(cksum "$main/.docs/features/core/index.md")"
sed -i.bak 's/status: active/status: draft/' "$main/.docs/features/core/alpha.md"
rm -f "$main/.docs/features/core/alpha.md.bak"
collision_rc=0
collision_dry_rc=0
collision_dry_out="$(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes 2>&1)" \
  || collision_dry_rc=$?
[[ "$collision_dry_rc" -eq 1 ]] \
  || fail "le dry-run doit échouer sur une collision avec un index manuel"
echo "$collision_dry_out" | grep -q 'conflict.*back/index.md' \
  || fail "le dry-run ne distingue pas la collision avec un index manuel"
(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/tmp/aic-feature-indexes-collision.out 2>&1) \
  || collision_rc=$?
[[ "$collision_rc" -eq 1 ]] || fail "un index manuel doit bloquer --apply"
head -n 1 "$main/.docs/features/back/index.md" | grep -Fqx '# Index manuel à préserver' \
  || fail "l'index manuel a été écrasé"
[[ "$core_before" == "$(cksum "$main/.docs/features/core/index.md")" ]] \
  || fail "une collision a permis une écriture partielle"
grep -q 'back/index.md' /tmp/aic-feature-indexes-collision.out \
  || fail "la collision ne cite pas le chemin concerné"
grep -q 'Déplace, fusionne' /tmp/aic-feature-indexes-collision.out \
  || fail "la collision ne donne pas de remédiation actionnable"
rm -f /tmp/aic-feature-indexes-collision.out "$main/.docs/features/back/index.md"
(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)

# Un symlink n'acquiert jamais la propriété, même si sa cible porte le marqueur.
outside_index="$tmp/outside-index.md"
printf '<!-- generated by ai_context; do not edit -->\n\n# Hors repo\n' > "$outside_index"
rm "$main/.docs/features/back/index.md"
ln -s "$outside_index" "$main/.docs/features/back/index.md"
symlink_rc=0
(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null 2>&1) \
  || symlink_rc=$?
[[ "$symlink_rc" -eq 1 && -L "$main/.docs/features/back/index.md" ]] \
  || fail "un index symlinké doit être refusé sans remplacement"
rm "$main/.docs/features/back/index.md"
(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)

# Un scope devenu vide perd seulement son ancien index géré.
rm "$main/.docs/features/back/space file.md"
delete_dry_out="$(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes)"
echo "$delete_dry_out" | grep -q 'delete.*back/index.md' \
  || fail "le dry-run ne distingue pas la suppression d'un index géré stale"
[[ -f "$main/.docs/features/back/index.md" ]] \
  || fail "le dry-run delete a supprimé l'index"
(cd "$main" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)
[[ ! -e "$main/.docs/features/back/index.md" ]] || fail "index d'un scope vide non supprimé"
[[ -f "$main/.docs/features/back/log.md" ]] || fail "log.md réservé supprimé par erreur"
grep -q 'back/index.md' "$main/.docs/features/index.md" \
  && fail "la racine route encore vers un scope vide"

# Hooks : index/log ne sont ni documentés comme feature, ni proposés au nudge.
rm -f "$main/.ai/.session-docs.log"
printf '{"tool_name":"Edit","tool_input":{"file_path":".docs/features/core/index.md"}}' \
  | (cd "$main" && bash .ai/scripts/auto-worklog-log.sh)
[[ ! -e "$main/.ai/.session-docs.log" ]] || fail "auto-worklog a traité index.md comme fiche"
nudge_out="$(printf '{"tool_name":"Edit","tool_input":{"file_path":"%s"}}' "$main/.docs/features/core/index.md" \
  | (cd "$main" && bash .ai/scripts/fiche-consolidation-nudge.sh))"
[[ -z "$nudge_out" ]] || fail "le nudge de consolidation a traité index.md comme fiche"

# Auto-worklog : docs_root avec préfixe ./ conserve la bonne clé scope/id.
rm -f "$main/.ai/.session-docs.log"
printf '{"tool_name":"Edit","tool_input":{"file_path":".docs/features/core/alpha.md"}}' \
  | (cd "$main" && AI_CONTEXT_DOCS_ROOT=./.docs bash .ai/scripts/auto-worklog-log.sh)
grep -Fxq 'core/alpha' "$main/.ai/.session-docs.log" \
  || fail "auto-worklog a manglé la clé avec AI_CONTEXT_DOCS_ROOT=./.docs"

# docs_root personnalisé.
custom="$tmp/custom"
copy_runtime "$custom"
write_feature "$custom/docs/features/api/one.md" one api "API One"
(cd "$custom" && AI_CONTEXT_DOCS_ROOT=docs bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)
[[ -f "$custom/docs/features/index.md" && -f "$custom/docs/features/api/index.md" ]] \
  || fail "docs_root=docs non respecté"
[[ ! -e "$custom/.docs/features/index.md" ]] || fail "docs_root custom a écrit sous .docs"

# Encodage TSV/Markdown : tabs éditoriaux normalisés, tab de fichier préservé.
tabs="$tmp/tabs"
copy_runtime "$tabs"
write_feature "$tabs/.docs/features/core/"$'tab\tfile.md' tab-file core $'Titre\ttabulé'
(cd "$tabs" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)
grep -Fq '[Titre tabulé](tab%09file.md)' "$tabs/.docs/features/core/index.md" \
  || fail "un tab a corrompu le TSV interne ou le lien Markdown"

# Le nom de scope est une donnée littérale, y compris avec un antislash.
backslash_scope="$tmp/backslash-scope"
copy_runtime "$backslash_scope"
scope_name='qa\ops'
write_feature "$backslash_scope/.docs/features/$scope_name/one.md" one "$scope_name" "QA One"
write_feature "$backslash_scope/.docs/features/$scope_name/two.md" two "$scope_name" "QA Two"
(cd "$backslash_scope" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)
grep -Fq '— 2 features' "$backslash_scope/.docs/features/index.md" \
  || fail "le compteur de scope interprète les antislashs"

# La migration refuse tout docs_root lexical ou physique hors repo.
bounded="$tmp/bounded"
outside_docs="$tmp/outside-docs"
copy_runtime "$bounded"
bounded_rc=0
(cd "$bounded" && AI_CONTEXT_DOCS_ROOT=../outside-docs bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null 2>&1) \
  || bounded_rc=$?
[[ "$bounded_rc" -eq 2 && ! -e "$outside_docs/features/index.md" ]] \
  || fail "okf-indexes a accepté un docs_root lexical hors repo"
mkdir -p "$outside_docs"
ln -s "$outside_docs" "$bounded/link-docs"
bounded_rc=0
(cd "$bounded" && AI_CONTEXT_DOCS_ROOT=link-docs bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null 2>&1) \
  || bounded_rc=$?
[[ "$bounded_rc" -eq 2 && ! -e "$outside_docs/features/index.md" ]] \
  || fail "okf-indexes a suivi un docs_root symlinké hors repo"

# Un répertoire de scope symlinké n'est jamais parcouru ni utilisé comme cible.
scope_link="$tmp/scope-link"
outside_scope="$tmp/outside-scope"
copy_runtime "$scope_link"
mkdir -p "$scope_link/.docs/features" "$outside_scope"
write_feature "$outside_scope/linked.md" linked linked "Linked outside"
ln -s "$outside_scope" "$scope_link/.docs/features/linked"
(cd "$scope_link" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)
[[ ! -e "$outside_scope/index.md" ]] \
  || fail "okf-indexes a écrit à travers un répertoire de scope symlinké"
grep -q 'Aucune feature documentée' "$scope_link/.docs/features/index.md" \
  || fail "okf-indexes a parcouru un répertoire de scope symlinké"

# Gate feat: : un index réservé ne satisfait pas la doc et ne compte pas comme code.
gate="$tmp/gate"
copy_runtime "$gate"
(
  cd "$gate" || exit 1
  git init -q || exit 1
  git config user.email test@example.com || exit 1
  git config user.name test || exit 1
  git config core.hooksPath /dev/null || exit 1
  git add -A || exit 1
  git commit -qm 'chore: fixture' || exit 1
  bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null || exit 1
  git add .docs/features/index.md || exit 1
  reserved_only_rc=0
  CLAUDE_COMMIT_MSG='feat: index seul' bash .ai/scripts/check-commit-features.sh >/dev/null 2>&1 \
    || reserved_only_rc=$?
  [[ "$reserved_only_rc" -eq 1 ]] || exit 1
  git reset -q || exit 1
  write_feature '.docs/features/core/gated.md' gated core 'Feature gated' || exit 1
  bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null || exit 1
  git add .docs/features/core/gated.md .docs/features/index.md .docs/features/core/index.md || exit 1
  CLAUDE_COMMIT_MSG='feat: feature et index générés' bash .ai/scripts/check-commit-features.sh >/dev/null || exit 1
) || fail "classification des index réservés incorrecte dans le gate feat:"

# Mesh vide : seule la racine déterministe est créée.
empty="$tmp/empty"
copy_runtime "$empty"
(cd "$empty" && bash .ai/scripts/aic.sh migrate okf-indexes --apply >/dev/null)
grep -q 'Aucune feature documentée' "$empty/.docs/features/index.md" \
  || fail "état vide de l'index racine absent"
scope_indexes="$(find "$empty/.docs/features" -mindepth 2 -maxdepth 2 -name index.md -print)"
[[ -z "$scope_indexes" ]] || fail "un mesh vide a généré un index de scope"

echo "✅ test-feature-markdown-indexes PASS"
